### ISSUE TITLE
Implement platescale variation across the focal plane

### ISSUE THREAD

**Issue by dkirkby** [desihub/specsim#24]
Splitting off some discussion in #5 into its own issue: the DESI plate scale varies a lot more across the focal plane than SDSS so this should be modeled, especially variations in the effective sky area leading to different throughputs.

The following plot from [desi-doc-329](https://desi.lbl.gov/DocDB/cgi-bin/private/ShowDocument?docid=329) summarizes the situation for DESI:

![untitled](https://cloud.githubusercontent.com/assets/185007/11671069/74d122da-9dba-11e5-8087-183f97c45ae8.png)

For the purposes of simulation, interpolation in a table of platescale vs radius and wavelength should be sufficiently accurate.

**Comment by dkirkby** [comment]
The ECHO22 platescale is tabulated in `desimodel/data/focalplane/platescale.txt` (SVN version), so no extra paths are necessary to read it via `desi.yaml`.  The file contents are described with this header:
```
# Echo 22 focal plane parameters from Figure 7 of DESI-0329v14                                         
# The plate scale varies with radius, and is different in the                                                   
# meridional (radial) direction vs. the                                                 
# sagittal (tangential/azimuthal) direction.  The table below                                           
# contains the F/#, Focal Length, and Plate Scale vs. radius for                                                       
# both the meridional and sagittal orientations at that radius.                                                 

# Columns:                                                     
# - Radius : radius from center of focal plane [mm]                                                     
# - Theta radial angle that has a centroid at this radius [deg]                                                 
# - MF/# : Meridional F/#                                                       
# - SF/# : Sagittal F/#                                                 
# - MFL  : Meridional focal length [m]                                                 
# - SFL  : Sagittal focal length [m]                                                   
# - MPS  : Meridional plate scale [um/arcsec]                                                   
# - SPS  : Sagittal plate scale [um/arcsec]                                                     
```
Rows correspond to r = 0 - 420 mm in steps of 1mm.  The corresponding theta values increase from 0 - 1.65 deg and, judging from Fig.7 of desi-0329, I guess they refer to the tilt of the surface normal and don't matter here (@sbailey - can you confirm?)

I assume that the sky projection of a circular hole in the plate with diameter D is an ellipse with major axes D/MPS (radial) and D/SPS (tangential).

**Comment by dkirkby** [comment]
Use the following regression test:
```
% quickspecsim -c desi --verbose
...
Fiber entrance area: 1.815 arcsec2
...
Median SNR in b camera = 1.165 / 0.5 Angstrom
Median SNR in r camera = 0.941 / 0.5 Angstrom
Median SNR in z camera = 0.742 / 0.5 Angstrom
```

Make the following replacement in the config file to get started:
```
-        # Averaged over the focal plane for 107.0 um physical diameter.
-        fiber_diameter: 1.52 arcsec
+        fiber_diameter: 107.0 um
+        plate_scale: 70.39473684210526 um / arcsec
```

This gives identical results, as expected.

**Comment by dkirkby** [comment]
Next step is to read `platescale.txt` using the existing config table-reading machinery:
```
    plate_scale:
        table:
            path: focalplane/platescale.txt
            format: ascii
            columns:
                radius: { index: 0, unit: mm }
                radial_scale: { index: 6, unit: um/arcsec }
                azimuthal_scale: { index: 7, unit: um/arcsec }
```
Then assume the fiber is centered in the focal plane (for now) to calculate its on-sky area:
```
% quickspecsim -c desi --verbose
...
Fiber entrance area: 1.973 arcsec2
...
Median SNR in b camera = 1.133 / 0.5 Angstrom
Median SNR in r camera = 0.913 / 0.5 Angstrom
Median SNR in z camera = 0.720 / 0.5 Angstrom
```
The fiber area has increased from its previous average value of 1.815 arcsec**2 to:
```
np.pi * (0.5*107/67.50706676) * (0.5*107/67.50706676) ~ 1.973 arcsec**2
```
since the scales ~ 67.5 um/arcsec at the plate center are smaller than the plate avg value ~ 70.4.

Median SNR values **decrease** by ~3%, compared with the area ratio (1.973/1.815) ~ 1.087.  This is reasonable since the sky background scales with fiber area, but we are assuming a fixed fiber acceptance fraction that does not know about the change in area.

**Comment by dkirkby** [comment]
Note that the new tabulated plate scale is optional, and falls back to a constant value which I am still using in the test config:
```
    plate_scale:
        constants:
            value: 70.4 um / arcsec
```

**Comment by sbailey** [comment]
> Rows correspond to r = 0 - 420 mm in steps of 1mm. The corresponding theta values increase from 0 - 1.65 deg and, judging from Fig.7 of desi-0329, I guess they refer to the tilt of the surface normal and don't matter here (@sbailey - can you confirm?)

I believe that is a correct interpretation.

**Comment by dkirkby** [comment]
The Instrument class now has methods that interpolate the radial and azimuthal plate scales as a function of radius, and calculate the field radius <-> field angle mapping by integrating the radial plate scale function.  There is also a method to make this plot:
```
import specsim.simulator
sim = specsim.simulator.Simulator('desi')
sim.instrument.plot_field_distortion()
```
![field_distortion](https://cloud.githubusercontent.com/assets/185007/17979034/963aa994-6aad-11e6-85f7-93c21233dbb7.png)

**Comment by dkirkby** [comment]
The last piece of this issue is to locate a simulated source in the focal plane.  Provide two ways to do this:
* specify focal_x, focal_y and airmass independently.
* specify source (ra,dec) and observing conditions:
  * boresight (ra,dec)
  * observatory location
  * exposure start time
  * atmospheric conditions (for refraction model)
To simplify setting the exposure time, allow an optional adjust_to_hour_angle parameter that uses the start time to specify the night then calculates the time during the night when the hour angle occurs.
The relevant pieces of the config file for the second option are (taken from the default `desi.yaml`):
```
source:
   ...
    location:
        sky: { coordinates: 0h 0d, frame: icrs }

observation:
    observatory: KPNO
    constants:
        exposure_time: 1000.0 s
        # Atmospheric pressure at the telescope (not at sea level) used
        # to calculate atmospheric refraction.  Leave commented out to use a
        # nominal value calculated for the observatory elevation.
        #pressure: 79 kPa
        # Air temperature at the telescope used to calculate atmospheric
        # refraction (but only has a small effect).
        temperature: 15 deg_C
        # Relative humidity (0-1) at the telescope used to calculate atmospheric
        # refraction (but only has a small effect).
        relative_humidity: 0.
    exposure_start:
        timestamp:
            when: 55000.5
            format: mjd
        # This optional parameter adjusts the timestamp by +/-12h to
        # achieve the specified hour angle for the boresight (ra, dec).
        #adjust_to_hour_angle: -0.5h
    pointing:
        sky:
            coordinates: 0h 0d
            frame: icrs
```

Examples using the command-line script:
```
# Calculate focal (x,y) and airmass from observing parameters and source (ra, dec)
% quickspecsim -c desi
Source at focal plane (x, y) = (0.0 mm rad / arcsec, 0.0 mm rad / arcsec).
Observing airmass is 1.262.
Median SNR in b camera = 1.094 / 0.5 Angstrom
Median SNR in r camera = 0.900 / 0.5 Angstrom
Median SNR in z camera = 0.711 / 0.5 Angstrom

# Specify focal (x,y) and airmass by hand
% quickspecsim -c desi --focal-x=50mm --focal-y=-50mm --airmass=1.2
Source at focal plane (x, y) = (50.0 mm, -50.0 mm).
Observing airmass is 1.200.
Median SNR in b camera = 1.105 / 0.5 Angstrom
Median SNR in r camera = 0.905 / 0.5 Angstrom
Median SNR in z camera = 0.714 / 0.5 Angstrom
```
